parameters:
#    arisgates_blog.example.class: Arisgates\BlogBundle\Example

services:
#    arisgates_blog.example:
#        class: %arisgates_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
